#+TITLE:  doom-module-email-mu4e

This package is a refactor of the current =mu4e= module on doom-emacs. It tries to modernize, and
enable more options to the =mu4e= user.

The code in this repository is a mix between [[https://github.com/hlissner][Henrik Lissner]]'s original code, [[https://github.com/tecosaur/emacs-config/blob/master/config.org][@tecosaur config]], and
some of my personal changes. BTW, if you didn't check [[https://github.com/tecosaur][@tecosaur]]'s config, do yourself a favor, and
spend some quality Elisp time there!

The core idea of this refactor is to simplify and beautify mu4e for users. I believe that all email
client should step up and help (if not do it entirely) user to setup her accounts and start
sending and receiving emails as fast as possible.

* Features / Roadmap

What follows is a non exhaustive list of features currently not implemented on the main doom mu4e
module. The checks on the checkbox indicate that the feature is already implemented in this
repository.

+ [X] Colorized accounts;
+ [X] All the icons for flags;
+ [X] Fix spacing on icons;
+ [X] Emil alerts;
+ [X] Better org-mode support to compose and send emails;
+ [X] Correct account for sending automatically set, or prompted
+ [X] Category icons;
+ [ ] Fix Gmail behavior per account;
+ [ ] Integrate @tecosaur's sync solution;
+ [ ] Sound on alarm;
+ [ ] Relative dates;
+ [ ] Thread folding;
+ [ ] Queueable and asynchronous message send;
+ [ ] Better xwidget integration;
+ [ ] Conversation view;
+ [ ] Doom doctor;
+ [ ] Install external dependencies;
+ [ ] Generate basic configuration for installed dependencies;
+ [ ] Expand Features section to include screenshots of all features;
+ [ ] GPG and  org-msg integration;
+ [ ] Replace mu4e main screen by a side panel with folders;
+ [ ] Match module colors to theme;
+ [ ] Document all functions;

* Installation

To install this module into your doom-emacs config, follow these instructions:

```sh
cd $DOOMDIR
mkdir modules
cd modules
git clone https://github.com/Townk/doom-module-email-mu4e.git email
```

* Extras

TBD

** Fetching emails

*** mbsync

TBD

*** offlineimap

TBD

*** goimapnotify

TBD

** Sending emails

*** msmtp

TBD

* Disclaimer

The icon asset used on the alert messages was created by Jonathan and distributed under public
domain license. You can find its source at his [[https://commons.wikimedia.org/wiki/File:Email_icon.svg][wikimedia page]].
